FROM node:24-alpine

WORKDIR /opt

COPY . /opt

RUN npm install && npm run build

RUN apk update && apk add apache2

RUN rm -rf /var/www/localhost/htdocs/*

RUN cp -rf dist/* /var/www/localhost/htdocs/

EXPOSE 80

CMD ["httpd","-D","FOREGROUND"]

