FROM ubuntu:latest

# Install Java and Maven
RUN apt update && apt install -y openjdk-17-jdk maven

# Set working directory
WORKDIR /opt

# Copy project files
COPY . /opt

# Build the project
RUN mvn clean package -DskipTests

# Expose port
EXPOSE 8080

WORKDIR /opt/target

# Run the jar
ENTRYPOINT ["java", "-jar", "student-registration-backend-0.0.1-SNAPSHOT.jar"]

